version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kok-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kok}
      POSTGRES_USER: ${POSTGRES_USER:-kok_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kok_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kok_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kok-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-kok_user}:${POSTGRES_PASSWORD:-kok_password}@postgres:5432/${POSTGRES_DB:-kok}
      JWT_SECRET: ${JWT_SECRET:-votre-secret-jwt-super-securise-changez-moi}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3001}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      FROM_EMAIL: ${FROM_EMAIL:-noreply@therapie-sensorimotrice.fr}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@therapie-sensorimotrice.fr}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin123!}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_DIR: /app/logs
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    container_name: kok-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: kok-network
